#!/bin/bash

code --install-extension shan.code-settings-sync
code --install-extension ms-vscode.go
code --install-extension ms-azuretools.vscode-docker
code --install-extension googlecloudtools.cloudcode
code --install-extension rogalmic.bash-debug
code --install-extension johnstoncode.svn-scm
code --install-extension bbenoist.vagrant
code --install-extension vscode-icons-team.vscode-icons
code --install-extension eamodio.gitlens
code --install-extension alefragnani.project-manager
code --install-extension quicktype.quicktype
code --install-extension alefragnani.bookmarks
code --install-extension ritwickdey.liveserver
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension formulahendry.code-runner
code --install-extension deerawan.vscode-faker
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension ms-vscode.cpptools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension GitHub.vscode-pull-request-github
code --install-extension ms-vscode.csharp
code --install-extension dotjoshjohnson.xml
code --install-extension wayou.vscode-todo-highlight
code --install-extension gruntfuggly.todo-tree
code --install-extension vscjava.vscode-java-pack
code --install-extension loiane.angular-extension-pack
code --install-extension vscoss.vscode-ansible